name: CI/CD - Develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.0"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Build Docker image
        run: docker build -t mode:latest .

      - name: Push Docker image
        run: docker push mode:latest

      - name: Deploy to EC2 instance
        run: |
          ssh -i "Mode Dev.pem" ubuntu@ec2-35-87-147-30.us-west-2.compute.amazonaws.com "docker pull mode:latest && \
          docker stop my-next-app || true && \
          docker rm my-next-app || true && \
          docker run -d -p 3000:3000 --name my-next-app my-next-app:latest"
